import React from "react";
import soccer_project from "../images/soccer-world.png"
import numGame from "../images/number-game-demo.png"

export default function Projects(){
    return (
        <div className="projects" id="projects">
            <h1 className="projects-title">Projects</h1>

            <div className="project-cards">

                <div className="soccer-project">
                    <img className="soccer-proj-img" src={soccer_project} alt="Soccer-Project"/>
                    <div className="tech-tags">
                        <p>HTML/CSS</p>
                        <p>JavaScript</p>
                        <p>Express.js</p>
                        <p>Node.js</p>
                    </div>
                    <p className="description">This website is similar to Tik Tok in that the user goes in and shares videos as well as view the dashboard. Once the user signs up, their information is stored in the database and used to verify log in attempts. <br/><hr></hr> Note: This is hosted on Glitch and may take a minute to start up.</p>

                    <a href="https://soccer-world-cus1172.glitch.me/auth/login" target="_blank" rel="noreferrer"><button className="buttons">Live Site</button></a>

                    <a href="https://github.com/miraclesanchez/Soccer-World" target="_blank" rel="noreferrer"><button className="buttons">Source Code</button></a>

                </div>
                <div className="guess-number">
                    <img className="num-game-img" src={numGame} alt="Num Game"/>
                    <div className="tech-tags">
                        <p>Java</p>
                        <p>Swing</p>
                        <p>Eclipse</p>
                    </div>
                    <p className="description">A random number is generated by the computer and the user has five guesses to get it right. The game provides hints with each guess telling the user to go higher or lower. Challenges allow you to get extra guesses<br/><hr></hr> Note: Click the button below for a demonstration!!</p><br/>

                    <a href="https://www.youtube.com/watch?v=7ceZDJbnkNI" target="_blank" rel="noreferrer"><button id="button" className="buttons">Demo Video</button></a>
                    <a href="https://github.com/miraclesanchez/Guess-the-Number-Game" target="_blank" rel="noreferrer"><button id="button" className="buttons">Source Code</button></a>
                </div>
            </div>
        </div>
    )
}