import soccer_project from "./images/soccer-world.png"
import numGame from "./images/number-game-demo.png"

export default[
    {
       img: soccer_project,
       techTag1: "HTML/CSS",
       techTag2: "JavaScript",
       techTag3: "Express.js",
       techTag4: "Node.js",
       description: "This website is similar to Tik Tok in that the user goes in and shares videos as well as view the dashboard. Once the user signs up, their information is stored in the database and used to verify log in attempts.",
       note: "Note: This is hosted on Glitch and may take a minute to start up.",
       projectLink: "https://soccer-world-cus1172.glitch.me/auth/login",
       sourceCodeLink: "https://github.com/miraclesanchez/Soccer-World"
    },
    {
        img: numGame,
       techTag1: "Java",
       techTag2: "Swing",
       techTag3: "Eclipse",
       description: "A random number is generated by the computer and the user has five guesses to get it right. The game provides hints with each guess telling the user to go higher or lower. Challenges allow you to get extra guesses.",
       note: "Note: Click the button below for a demonstration!!",
       projectLink: "https://www.youtube.com/watch?v=7ceZDJbnkNI",
       sourceCodeLink: "https://github.com/miraclesanchez/Guess-the-Number-Game"
    }
]